package com.abhishek.chatapp.theme

import androidx.compose.ui.graphics.Color

//Light Theme Colors
val md_theme_light_primary = Color(0xFF1976D2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBDEFB)
val md_theme_light_onPrimaryContainer = Color(0xFF002F6C)
val md_theme_light_secondary = Color(0xFF03A9F4)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE1F5FE)
val md_theme_light_onSecondaryContainer = Color(0xFF01579B)
val md_theme_light_tertiary = Color(0xFF00BCD4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB2EBF2)
val md_theme_light_onTertiaryContainer = Color(0xFF006064)
val md_theme_light_error = Color(0xFFB00020)
val md_theme_light_errorContainer = Color(0xFFFCD8DF)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF8C0009)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF90CAF9)

//Dark Theme Colors
val md_theme_dark_primary = Color(0xFF90CAF9)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF00497B)
val md_theme_dark_onPrimaryContainer = Color(0xFFBBDEFB)
val md_theme_dark_secondary = Color(0xFF81D4FA)
val md_theme_dark_onSecondary = Color(0xFF003C50)
val md_theme_dark_secondaryContainer = Color(0xFF004F65)
val md_theme_dark_onSecondaryContainer = Color(0xFFE1F5FE)
val md_theme_dark_tertiary = Color(0xFF80DEEA)
val md_theme_dark_onTertiary = Color(0xFF003D40)
val md_theme_dark_tertiaryContainer = Color(0xFF004F54)
val md_theme_dark_onTertiaryContainer = Color(0xFFB2EBF2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE1E2E5)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFE1E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF2B2930)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E5)
val md_theme_dark_inversePrimary = Color(0xFF1976D2)